stages:
  train:
    cmd: python3 train.py
    deps:
      - train.py
      - data/iris.csv
      - params.yaml
    params:
      - split.test_size
      - split.random_state
      - train.max_depth
      - train.random_state
      - train.model_output_path
      - train.model_name
      - train.experiment_name
      - train.tracking_uri
      - train.storage_location
    outs:
      - artifacts/model_1.joblib

  test:
    cmd: python3 test.py
    deps:
      - test.py
      - artifacts/model_1.joblib
    outs:
      - logs/sanity_check.log
